/**
 * Enum representing different segments for the NBA API.
 */
export enum SEGMENT {
  ABBV = 'abbv',
  ABBV_PARAM = ':abbv',
  ALL_TIME = 'all-time',
  ALL = 'all',
  API = 'api',
  AST = 'ast',
  ASSIST = 'assist',
  AWARD = 'award',
  CAREER = 'career',
  COMMON = 'common',
  COMPARE = 'compare',
  DRAFT = 'draft',
  FANTASY = 'fantasy',
  FIND = 'find',
  FINDER = 'finder',
  FRANCHISE = 'franchise',
  GAME = 'game',
  HISTORY = 'history',
  ID = ':id',
  INFO = 'info',
  LEADER = 'leader',
  LEAGUE = 'league',
  MATCHUPS = 'matchups',
  PLAYER = 'player',
  PLAYER_1_ID = ':player1Id',
  PLAYER_2_ID = ':player2Id',
  PT = 'pt',
  POINT = 'point',
  PTS = 'pts',
  ROTATION = 'rotation',
  ROOT = '/',
  ROSTER = 'roster',
  SCOREBOARD = 'scoreboard',
  SDK = 'sdk',
  STATE = 'state',
  STATE_PARAM = ':state',
  SYNERGY = 'synergy',
  TEAM = 'team',
  TOTAL = 'total',
  USER = 'user',
  VS = 'vs'
}
