/**
 * Enum representing different segments for the NBA API.
 */
export enum SEGMENT {
  ABBV = 'abbv',
  ABBV_PARAM = ':abbv',
  ALL_TIME = 'all-time',
  ALL = 'all',
  API = 'api',
  AST = 'ast',
  ASSIST = 'assist',
  AWARD = 'award',
  CAREER = 'career',
  COMMON = 'common',
  DRAFT = 'draft',
  FANTASY = 'fantasy',
  FIND = 'find',
  FRANCHISE = 'franchise',
  HISTORY = 'history',
  ID = ':id',
  INFO = 'info',
  LEADER = 'leader',
  PLAYER = 'player',
  PT = 'pt',
  POINT = 'point',
  PTS = 'pts',
  ROTATION = 'rotation',
  SCOREBOARD = 'scoreboard',
  SDK = 'sdk',
  STATE = 'state',
  STATE_PARAM = ':state',
  SYNERGY = 'synergy',
  TEAM = 'team',
  TOTAL = 'total',
  USER = 'user'
}
