export const TAGS = {
  ANSWER: 'Answer',
  FRANCHISE: 'Franchise',
  GAME: 'Game',
  GAME_STATS: 'GameStats',
  LEAGUE: 'League',
  PER36: 'Per36',
  PER48: 'Per48',
  PLAYER: 'Player',
  PLAYER_STATS: 'PlayerStats',
  PLAYER_STATS_OVERVIEW: 'PlayerStatsOverview',
  PLAYER_PLAYOFFS_STATS: 'PlayerPlayoffsStats',
  PLAYER_REGULAR_SEASON_STATS: 'PlayerRegularSeasonStats',
  PLAYOFFS_STATS: 'PlayoffsStats',
  QUESTION: 'Question',
  ROUND: 'Round',
  SCORE: 'Score',
  SDK: 'SDK',
  STATS: 'Stats',
  TEAM: 'Team',
  TEAM_STATS: 'TeamStats',
  TEAM_STATS_OVERVIEW: 'TeamStatsOverview',
  TEAM_PLAYOFFS_STATS: 'TeamPlayoffsStats',
  TEAM_REGULAR_SEASON_STATS: 'TeamRegularSeasonStats',
  TOTALS: 'Totals'
}
